version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.API/Dockerfile
    ports:
      - "7175:7175"
    environment:
      - ASPNETCORE_URLS=http://*:7175
    depends_on: [mssql, seq_logs]
  conferenceattendees.web:
    image: ${DOCKER_REGISTRY-}conferenceattendeesweb
    build:
      context: .
      dockerfile: ConferenceAttendees.Web/Dockerfile
    ports:
      - "7066:7066"
    environment:
      - ASPNETCORE_URLS=http://*:7066
    depends_on:
       - conferenceattendees.api
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlConference
    hostname: mssql
    environment: 
      - MSSQL_SA_PASSWORD=admin@123
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1400:1433"   
  seq_logs:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
   

